function StartAnalysis()


testfiles = { ...
'C:\Users\owenj\matlab_workspace\paperanalysis\testdata\SEFI2014_0025_final.pdf', ...
'C:\Users\owenj\matlab_workspace\paperanalysis\testdata\SEFI2014_0140_final.pdf', ...
'C:\Users\owenj\matlab_workspace\paperanalysis\testdata\SEFI2014_0062_final.pdf', ...
'C:\Users\owenj\matlab_workspace\paperanalysis\testdata\SEFI2014_0029_final.txt', ...
'C:\Users\owenj\matlab_workspace\paperanalysis\testdata\SEFI2014_0002_final.doc', ...
'C:\Users\owenj\matlab_workspace\paperanalysis\testdata\SEFI2014_0011_final.docx' ...
}';

docparser = ParseFiles(testfiles, 'TestProject');
% docparser.runSequentially();
% generateSemanticSurface(docparser)
% generateWordCloud(docparser.uniqueWords, docparser.wordCounts);
    
end

