function [docTitle, allWords] = parseOneTextFile(filename)
%PARSEONETEXTFILE Parses a single text file and returns its title and a
%cell array containing all words in the text file (one cell per word).
docTitle = 'test paper';
allWords = {'apple', 'apricot', 'avocado', 'banana', 'berry', 'blackberry', ...
        'blood orange', 'blueberry', 'cantaloupe', 'cherry', 'citron', 'citrus', ...
        'coconut','crabapple', 'cranberry', 'currant', 'date', 'dragonfruit', ...
        'durian', 'elderberry', 'fig', 'grape', 'grapefruit', 'guava', 'honeydew', ...
        'kiwi', 'kumquat', 'lemon', 'lime', 'lingonberry', 'loquat', 'lychee', ...
        'mandarin orange', 'mango', 'melon', 'nectarine', 'orange', 'papaya', ...
        'passion fruit', 'peach', 'pear', 'persimmon', 'pineapple', 'plantain', ...
        'plum', 'pomegranite', 'prune', 'quince', 'raisin', 'raspberry', ...
        'star fruit', 'strawberry', 'tangelo', 'tangerine', 'watermelon', ...
        'apricot', 'avocado', 'banana', 'berry', 'blackberry', 'blood orange'};

end

