cla reset
clear variables
fontBlockSize = 0.02;
prettyFonts = {'Century Gothic', 'Cooper Black', 'Magneto Bold'};

cx = 0.2;
cy = 0.8;

scatter(cx, cy);
xlim([0 1]);
ylim([0 1]);

wh1 = text('String', 'string1', ...
    'FontName', prettyFonts{randi(numel(prettyFonts), 1)}, ... % random pretty font
    'Color', rand(1,3), ...
    'Margin', 1, ...
    'FontUnits', 'normalized', ...
    'FontSize', 4*fontBlockSize, ...
    'Units', 'data', ... % 'normalized', ... %
    'VerticalAlignment', 'middle', ...
    'HorizontalAlignment', 'center', ...
    'Position', [0.5,1] ...
    );
whL = text('String', 'wh2 added to', ...
    'FontName', prettyFonts{randi(numel(prettyFonts), 1)}, ... % random pretty font
    'Color', rand(1,3), ...
    'Margin', 1, ...
    'FontUnits', 'normalized', ...
    'FontSize', 3*fontBlockSize, ...
    'Units', 'data', ... % 'normalized', ... %
    'VerticalAlignment', 'middle', ...
    'HorizontalAlignment', 'center', ...
    'Position', [0.5,1] ...
    );
whR = text('String', 'or is it?', ...
    'FontName', prettyFonts{randi(numel(prettyFonts), 1)}, ... % random pretty font
    'Color', rand(1,3), ...
    'Margin', 1, ...
    'FontUnits', 'normalized', ...
    'FontSize', 3*fontBlockSize, ...
    'Units', 'data', ... % 'normalized', ... %
    'VerticalAlignment', 'middle', ...
    'HorizontalAlignment', 'center', ...
    'Position', [0.5,1] ...
    );

wr = WordClusterRow(wh1, 'middle', cx, cy);
wr = wr.addWordLeft(whL);
wr = wr.addWordRight(whR);
wr = wr.addWordRight(whR);
% wr = wr.repositionRow(0.64, 0.2)